spring:
  application:
    name: lock-test2
perfect:
  lock:
    redis:
      aop-priority: 1
      prefix: "perfect_lock2:"
  test:
    redis:
      address: redis://192.168.0.103:6379
      password: lige@2020
debug: true